In [1]:
import torch
import torch.nn.functional as F

In [6]:
torch.manual_seed(0)

x = torch.rand(size=(2, 3, 3))
y = torch.rand(size=(2, 3, 3))
print(x.view(1, -1))
print(y)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000]])
tensor([[[0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742],
         [0.4194, 0.5529, 0.9527]],

        [[0.0362, 0.1852, 0.3734],
         [0.3051, 0.9320, 0.1759],
         [0.2698, 0.1507, 0.0317]]])


In [7]:
x_normalize = F.normalize(x.view(1, -1))
x_normalize

tensor([[0.2264, 0.3505, 0.0404, 0.0602, 0.1403, 0.2893, 0.2236, 0.4090, 0.2079,
         0.2885, 0.1592, 0.1833, 0.0102, 0.0770, 0.1341, 0.2366, 0.3183, 0.3650]])